project:
  type : website
  output-dir : docs

website: 
  search: true 
  title: "Datacamp pour le master SEP"
  reader-mode: true 
  
  navbar:
    left:
      - text: "Accueil"
        file: "index.qmd"
      - text: "M1 SEP"
        file: "M1SEP.qmd"
      - text: "Exercices"
        file: "Exercices.qmd"
      - text: "Quizz"
        file: "Quizz.qmd"
      - text: "Logiciels"
        file: "LOGICIELS.qmd"
        
format:
  html:
    toc: true 
    page-layout: full 
    theme: cosmo

