website:
  title: "DATA Camp du master SEP"
  navbar:
    left:
      - href: "index.qmd"
        text: "Accueil"
      - href: "M1SEP.qmd"
        text: "M1 SEP"
      - href: "M2SEP.qmd"
        text: "M2 SEP"
      - href: "LOGICIELS.qmd"
        text: "Logiciels"

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport

editor: visual

